/* ═══════════════════════════════════════════════════════════
   GAME DATA – Chinese Wisdom Phrases & Chengyu (成語)
   Year of the Horse 2026 | JPMC Glasgow
   Curated collection of authentic Chinese New Year blessings,
   proverbs, and four-character idioms (成語 chéngyǔ)
   ═══════════════════════════════════════════════════════════ */

// ─── Wisdom Phrase Categories ───────────────────────────────
// Each phrase is a complete Chinese blessing or chengyu
// The game presents 2 choices per round; player picks one per line

// ── Horse-Year Specific Wisdom (馬年專屬) ──
const HORSE_PHRASES = [
  {
    chinese: '馬到成功',
    pinyin: 'Mǎ dào chéng gōng',
    english: 'Success upon the horse\'s arrival',
    meaning: 'Instant success — as swift as a galloping horse',
    luck: 5,
    rare: true,
    category: 'horse',
    culturalNote: 'The most iconic Horse-year chengyu! It means achieving immediate success, like a war horse charging to victory.',
  },
  {
    chinese: '龍馬精神',
    pinyin: 'Lóng mǎ jīng shén',
    english: 'Spirit of the dragon-horse',
    meaning: 'Vigorous spirit and boundless energy',
    luck: 5,
    rare: true,
    category: 'horse',
    culturalNote: 'Combines the mythical power of the dragon with the stamina of the horse — the ultimate wish for vitality!',
  },
  {
    chinese: '一馬當先',
    pinyin: 'Yī mǎ dāng xiān',
    english: 'One horse takes the lead',
    meaning: 'To be a trailblazer, leading the way',
    luck: 4,
    rare: true,
    category: 'horse',
    culturalNote: 'From ancient cavalry formations — the bravest rider charges ahead. A wish for leadership and courage.',
  },
  {
    chinese: '萬馬奔騰',
    pinyin: 'Wàn mǎ bēn téng',
    english: 'Ten thousand horses galloping',
    meaning: 'A scene of great momentum and prosperity',
    luck: 5,
    rare: true,
    category: 'horse',
    culturalNote: 'Evokes the magnificent image of thousands of horses thundering across the plains — unstoppable progress!',
  },
  {
    chinese: '快馬加鞭',
    pinyin: 'Kuài mǎ jiā biān',
    english: 'Spur on the swift horse',
    meaning: 'Accelerate progress, push forward with vigour',
    luck: 4,
    rare: false,
    category: 'horse',
    culturalNote: 'Encourages doubling down on effort when things are already going well — keep the momentum!',
  },
  {
    chinese: '天馬行空',
    pinyin: 'Tiān mǎ xíng kōng',
    english: 'Heavenly horse soaring through the sky',
    meaning: 'Boundless creativity and imagination',
    luck: 4,
    rare: true,
    category: 'horse',
    culturalNote: 'Describes unlimited imagination, like the mythical Tianma (heavenly horse) that flies through clouds.',
  },
  {
    chinese: '馬年大吉',
    pinyin: 'Mǎ nián dà jí',
    english: 'Great fortune in the Year of the Horse',
    meaning: 'Wishing great luck in this Horse year',
    luck: 4,
    rare: false,
    category: 'horse',
    culturalNote: 'A classic zodiac-year greeting — simple, heartfelt, and perfectly suited for 2026!',
  },
  {
    chinese: '策馬奔騰',
    pinyin: 'Cè mǎ bēn téng',
    english: 'Ride the galloping horse forward',
    meaning: 'Charge ahead boldly toward your dreams',
    luck: 4,
    rare: false,
    category: 'horse',
    culturalNote: 'Symbolises seizing opportunities with bold action — saddle up and ride toward your goals!',
  },
];

// ── Classic New Year Blessings (經典賀詞) ──
const BLESSING_PHRASES = [
  {
    chinese: '恭喜發財',
    pinyin: 'Gōng xǐ fā cái',
    english: 'Wishing you prosperity',
    meaning: 'May wealth and fortune come your way',
    luck: 4,
    rare: false,
    category: 'blessing',
    culturalNote: 'The single most spoken Chinese New Year greeting worldwide! Originally Cantonese, now universal.',
  },
  {
    chinese: '新年快樂',
    pinyin: 'Xīn nián kuài lè',
    english: 'Happy New Year',
    meaning: 'Joy and happiness in the new year',
    luck: 3,
    rare: false,
    category: 'blessing',
    culturalNote: 'The modern standard greeting, influenced by Western "Happy New Year" but now deeply embedded in Chinese culture.',
  },
  {
    chinese: '萬事如意',
    pinyin: 'Wàn shì rú yì',
    english: 'May all go as you wish',
    meaning: 'Everything unfolds according to your heart\'s desires',
    luck: 4,
    rare: false,
    category: 'blessing',
    culturalNote: 'One of the "big four" New Year blessings. 如意 (rúyì) also refers to a ceremonial sceptre symbolising good fortune.',
  },
  {
    chinese: '吉祥如意',
    pinyin: 'Jí xiáng rú yì',
    english: 'Auspicious and as you wish',
    meaning: 'Good omens and fulfilled wishes',
    luck: 4,
    rare: false,
    category: 'blessing',
    culturalNote: 'Combines 吉祥 (auspicious) with 如意 (as wished) — a double blessing for perfect outcomes.',
  },
  {
    chinese: '金玉滿堂',
    pinyin: 'Jīn yù mǎn táng',
    english: 'Gold and jade fill the hall',
    meaning: 'May your home overflow with treasures and abundance',
    luck: 5,
    rare: true,
    category: 'blessing',
    culturalNote: 'From the Tao Te Ching — originally about spiritual wealth, now a wish for material and spiritual abundance.',
  },
  {
    chinese: '年年有餘',
    pinyin: 'Nián nián yǒu yú',
    english: 'Surplus every year',
    meaning: 'May you always have more than enough',
    luck: 4,
    rare: false,
    category: 'blessing',
    culturalNote: '餘 (surplus) sounds like 魚 (fish), which is why fish is served at every New Year dinner — never fully eaten!',
  },
  {
    chinese: '花開富貴',
    pinyin: 'Huā kāi fù guì',
    english: 'Blossoming flowers bring wealth',
    meaning: 'Prosperity blooms like flowers in spring',
    luck: 4,
    rare: false,
    category: 'blessing',
    culturalNote: 'Peony (牡丹) is the "king of flowers" in China and symbolises wealth and honour. This phrase is its blessing.',
  },
  {
    chinese: '招財進寶',
    pinyin: 'Zhāo cái jìn bǎo',
    english: 'Ushering in wealth and treasures',
    meaning: 'Attracting fortune and precious things into your life',
    luck: 5,
    rare: true,
    category: 'blessing',
    culturalNote: 'Often written as a single combined character on red paper and hung on doors during New Year!',
  },
  {
    chinese: '福壽雙全',
    pinyin: 'Fú shòu shuāng quán',
    english: 'Both fortune and longevity',
    meaning: 'May you enjoy both happiness and a long life',
    luck: 4,
    rare: false,
    category: 'blessing',
    culturalNote: 'The two greatest wishes combined: 福 (fortune/happiness) and 壽 (longevity). Especially given to elders.',
  },
  {
    chinese: '大展鴻圖',
    pinyin: 'Dà zhǎn hóng tú',
    english: 'Unfurl grand ambitions',
    meaning: 'May your great plans be realised magnificently',
    luck: 4,
    rare: false,
    category: 'blessing',
    culturalNote: '鴻圖 literally means "great blueprint" — a wish for career success and achieving ambitious goals.',
  },
];

// ── Prosperity & Career Wisdom (事業財富) ──
const PROSPERITY_PHRASES = [
  {
    chinese: '步步高升',
    pinyin: 'Bù bù gāo shēng',
    english: 'Rising higher with each step',
    meaning: 'Steady advancement in career and life',
    luck: 4,
    rare: false,
    category: 'prosperity',
    culturalNote: 'A favourite blessing for colleagues! Also the name of a popular New Year rice cake — eaten for "rising fortune".',
  },
  {
    chinese: '財源廣進',
    pinyin: 'Cái yuán guǎng jìn',
    english: 'Wealth flows in from all directions',
    meaning: 'May money come to you from every source',
    luck: 5,
    rare: true,
    category: 'prosperity',
    culturalNote: 'The ultimate business blessing — often displayed at shop entrances during New Year.',
  },
  {
    chinese: '一帆風順',
    pinyin: 'Yī fān fēng shùn',
    english: 'Smooth sailing with fair winds',
    meaning: 'Everything goes smoothly without obstacles',
    luck: 4,
    rare: false,
    category: 'prosperity',
    culturalNote: 'Originates from sailing culture — when the wind fills your sail perfectly, the journey is effortless.',
  },
  {
    chinese: '前程似錦',
    pinyin: 'Qián chéng sì jǐn',
    english: 'A future as brilliant as brocade',
    meaning: 'A splendid and promising road ahead',
    luck: 4,
    rare: false,
    category: 'prosperity',
    culturalNote: '錦 (brocade/silk) was the most precious fabric in ancient China — your future is woven with golden threads!',
  },
  {
    chinese: '生意興隆',
    pinyin: 'Shēng yì xīng lóng',
    english: 'Business flourishes',
    meaning: 'May your enterprises thrive and prosper',
    luck: 4,
    rare: false,
    category: 'prosperity',
    culturalNote: 'The go-to blessing for business owners. Often paired with 財源廣進 on shop door couplets.',
  },
  {
    chinese: '心想事成',
    pinyin: 'Xīn xiǎng shì chéng',
    english: 'Whatever the heart desires comes true',
    meaning: 'All your wishes and dreams are fulfilled',
    luck: 4,
    rare: false,
    category: 'prosperity',
    culturalNote: 'Perhaps the most universally loved blessing — it promises that your deepest wishes will manifest.',
  },
  {
    chinese: '一本萬利',
    pinyin: 'Yī běn wàn lì',
    english: 'Small investment, ten-thousand-fold return',
    meaning: 'Great profits from modest beginnings',
    luck: 5,
    rare: true,
    category: 'prosperity',
    culturalNote: 'Originally from merchant culture — a wish that every venture yields extraordinary returns.',
  },
  {
    chinese: '鵬程萬里',
    pinyin: 'Péng chéng wàn lǐ',
    english: 'A Peng bird\'s journey of ten thousand miles',
    meaning: 'A limitless and magnificent future',
    luck: 4,
    rare: false,
    category: 'prosperity',
    culturalNote: 'From Zhuangzi\'s famous fable — the mythical Peng bird soars 90,000 li. A wish for boundless achievement.',
  },
];

// ── Health & Harmony (健康和諧) ──
const HARMONY_PHRASES = [
  {
    chinese: '闔家歡樂',
    pinyin: 'Hé jiā huān lè',
    english: 'Joy for the whole family',
    meaning: 'Happiness and laughter throughout your household',
    luck: 4,
    rare: false,
    category: 'harmony',
    culturalNote: 'Family reunion (團圓) is the heart of Chinese New Year. This blessing captures that warmth.',
  },
  {
    chinese: '身體健康',
    pinyin: 'Shēn tǐ jiàn kāng',
    english: 'Good health',
    meaning: 'Wishing you a strong and healthy body',
    luck: 3,
    rare: false,
    category: 'harmony',
    culturalNote: 'Traditionally the first wish given to elders — health is considered the foundation of all fortune.',
  },
  {
    chinese: '歲歲平安',
    pinyin: 'Suì suì píng ān',
    english: 'Peace year after year',
    meaning: 'Safety and tranquility through every season',
    luck: 4,
    rare: false,
    category: 'harmony',
    culturalNote: '歲 (age/year) is a homophone of 碎 (shatter) — so if something breaks during New Year, say this immediately!',
  },
  {
    chinese: '竹報平安',
    pinyin: 'Zhú bào píng ān',
    english: 'Bamboo heralds peace',
    meaning: 'News from afar brings only good tidings',
    luck: 3,
    rare: false,
    category: 'harmony',
    culturalNote: 'In ancient China, letters were written on bamboo slips. This wishes that every message you receive is peaceful.',
  },
  {
    chinese: '和氣生財',
    pinyin: 'Hé qì shēng cái',
    english: 'Harmony breeds wealth',
    meaning: 'A peaceful attitude generates prosperity',
    luck: 4,
    rare: false,
    category: 'harmony',
    culturalNote: 'A profound business philosophy — treating people kindly leads to success. Displayed in many Chinese shops.',
  },
  {
    chinese: '國泰民安',
    pinyin: 'Guó tài mín ān',
    english: 'Nation prosperous, people at peace',
    meaning: 'Prosperity for the country and safety for all',
    luck: 3,
    rare: false,
    category: 'harmony',
    culturalNote: 'A grand blessing for the collective — wishing peace and prosperity not just for oneself, but for all.',
  },
  {
    chinese: '天倫之樂',
    pinyin: 'Tiān lún zhī lè',
    english: 'The joy of family bonds',
    meaning: 'The deep happiness of being together with loved ones',
    luck: 4,
    rare: false,
    category: 'harmony',
    culturalNote: '天倫 means natural family relationships — the purest form of happiness according to Chinese philosophy.',
  },
  {
    chinese: '吉慶有餘',
    pinyin: 'Jí qìng yǒu yú',
    english: 'Boundless celebrations and joy',
    meaning: 'May your happiness know no limits',
    luck: 4,
    rare: false,
    category: 'harmony',
    culturalNote: 'Combines good fortune (吉), celebration (慶), and surplus (餘) — an overflow of joyous occasions!',
  },
];

// ── Wisdom & Virtue Chengyu (品德智慧) ──
const WISDOM_PHRASES = [
  {
    chinese: '學富五車',
    pinyin: 'Xué fù wǔ chē',
    english: 'Knowledge fills five carts',
    meaning: 'Immensely learned and wise',
    luck: 3,
    rare: false,
    category: 'wisdom',
    culturalNote: 'From Zhuangzi — in ancient times, books were written on bamboo strips so heavy that five carts were needed!',
  },
  {
    chinese: '百尺竿頭',
    pinyin: 'Bǎi chǐ gān tóu',
    english: 'Atop a hundred-foot pole',
    meaning: 'Having achieved great heights, strive for even more',
    luck: 3,
    rare: false,
    category: 'wisdom',
    culturalNote: 'A Buddhist proverb — even at the peak, one should take one more step forward. Never stop growing!',
  },
  {
    chinese: '厚德載物',
    pinyin: 'Hòu dé zài wù',
    english: 'Great virtue carries all things',
    meaning: 'A person of deep virtue can embrace everything',
    luck: 4,
    rare: true,
    category: 'wisdom',
    culturalNote: 'From the I Ching (Book of Changes) — the motto of Tsinghua University. Virtue is the foundation of greatness.',
  },
  {
    chinese: '自強不息',
    pinyin: 'Zì qiáng bù xī',
    english: 'Constant self-improvement',
    meaning: 'Never cease to strengthen and better yourself',
    luck: 4,
    rare: true,
    category: 'wisdom',
    culturalNote: 'Also from the I Ching — paired with 厚德載物 as the twin pillars of Chinese self-cultivation philosophy.',
  },
  {
    chinese: '迎春接福',
    pinyin: 'Yíng chūn jiē fú',
    english: 'Welcome spring, receive blessings',
    meaning: 'Embrace the new season and the fortune it brings',
    luck: 3,
    rare: false,
    category: 'wisdom',
    culturalNote: 'A poetic expression — Spring Festival is literally about welcoming spring, when nature renews and fortune arrives.',
  },
  {
    chinese: '飲水思源',
    pinyin: 'Yǐn shuǐ sī yuán',
    english: 'When drinking water, remember its source',
    meaning: 'Be grateful and never forget where you came from',
    luck: 3,
    rare: false,
    category: 'wisdom',
    culturalNote: 'A timeless value in Chinese culture — gratitude and remembering one\'s roots, especially during New Year reunions.',
  },
];

// ── Taboo Phrases (禁忌語) — culturally inappropriate for New Year ──
const TABOO_PHRASES = [
  {
    chinese: '四季發財',
    pinyin: 'Sì jì fā cái',
    english: 'Prosperity in four seasons',
    meaning: 'Sounds auspicious but "四" (four) sounds like death!',
    luck: -3,
    rare: false,
    taboo: true,
    category: 'taboo',
    culturalNote: '四 (sì, four) sounds exactly like 死 (sǐ, death). The number 4 is strictly avoided during celebrations — buildings often skip the 4th floor!',
  },
  {
    chinese: '別來無恙',
    pinyin: 'Bié lái wú yàng',
    english: 'Hope all is well since we parted',
    meaning: '"別" (part/separate) is inauspicious at New Year',
    luck: -2,
    rare: false,
    taboo: true,
    category: 'taboo',
    culturalNote: 'While normally polite, using 別 (to separate/part) during New Year suggests separation — taboo when families should be reuniting!',
  },
  {
    chinese: '破釜沉舟',
    pinyin: 'Pò fǔ chén zhōu',
    english: 'Smash the pots, sink the boats',
    meaning: '"破" (break) is deeply unlucky during festivities',
    luck: -3,
    rare: false,
    taboo: true,
    category: 'taboo',
    culturalNote: 'Breaking anything during New Year invites bad luck. If something breaks accidentally, quickly say 歲歲平安 (peace year after year)!',
  },
  {
    chinese: '空穴來風',
    pinyin: 'Kōng xué lái fēng',
    english: 'Wind from an empty cave',
    meaning: '"空" (empty) symbolises poverty and lack',
    luck: -2,
    rare: false,
    taboo: true,
    category: 'taboo',
    culturalNote: 'Emptiness during New Year is a terrible omen. Keep your rice jars full and your wallet stuffed — even symbolically!',
  },
  {
    chinese: '哭笑不得',
    pinyin: 'Kū xiào bù dé',
    english: 'Can neither cry nor laugh',
    meaning: '"哭" (cry) brings sorrow for the entire year',
    luck: -3,
    rare: false,
    taboo: true,
    category: 'taboo',
    culturalNote: 'Crying on New Year\'s Day is believed to bring tears throughout the year. Only happy words and laughter allowed!',
  },
  {
    chinese: '債台高築',
    pinyin: 'Zhài tái gāo zhù',
    english: 'Debts piled high as a tower',
    meaning: 'All debts must be cleared before New Year!',
    luck: -4,
    rare: false,
    taboo: true,
    category: 'taboo',
    culturalNote: 'Tradition demands settling ALL debts before midnight on New Year\'s Eve. Carrying debt into the new year curses your finances!',
  },
  {
    chinese: '落花流水',
    pinyin: 'Luò huā liú shuǐ',
    english: 'Fallen flowers, flowing water',
    meaning: 'Suggests decline and things falling apart',
    luck: -2,
    rare: false,
    taboo: true,
    category: 'taboo',
    culturalNote: 'While poetic, this phrase implies decay and loss. New Year should be about blooming (花開), not falling (落花)!',
  },
  {
    chinese: '半途而廢',
    pinyin: 'Bàn tú ér fèi',
    english: 'Give up halfway',
    meaning: 'Quitting midway — terrible omen for new beginnings',
    luck: -3,
    rare: false,
    taboo: true,
    category: 'taboo',
    culturalNote: 'Starting the year with a phrase about giving up? The worst omen imaginable! New Year is about fresh starts and perseverance.',
  },
];

// ─── Combine All Lucky Phrases ──────────────────────────────
const ALL_LUCKY_PHRASES = [
  ...HORSE_PHRASES,
  ...BLESSING_PHRASES,
  ...PROSPERITY_PHRASES,
  ...HARMONY_PHRASES,
  ...WISDOM_PHRASES,
];

// ─── Greeting Scroll Templates ──────────────────────────────
// Each template defines a narrative arc for building a blessing scroll
const SCROLL_TEMPLATES = [
  {
    title: '🐴 Horse Year Fortune Scroll',
    intro: '{name}\'s New Year Blessing Scroll',
    sections: [
      { label: '🐴 Horse Year Blessing', pool: 'horse',      required: true },
      { label: '🧧 New Year Greeting',   pool: 'blessing',   required: true },
      { label: '💰 Prosperity Wish',     pool: 'prosperity', required: true },
      { label: '🏮 Harmony & Peace',     pool: 'harmony',    required: true },
      { label: '📜 Wisdom for the Year', pool: 'wisdom',     required: true },
      { label: '🐴 Galloping Finale',    pool: 'horse',      required: true },
    ],
  },
  {
    title: '🏮 Golden Blessing Scroll',
    intro: '{name}\'s Lunar New Year Wishes',
    sections: [
      { label: '🎆 Opening Blessing',    pool: 'blessing',   required: true },
      { label: '🐴 Horse Spirit',        pool: 'horse',      required: true },
      { label: '💰 Wealth & Career',     pool: 'prosperity', required: true },
      { label: '🏮 Family & Peace',      pool: 'harmony',    required: true },
      { label: '🐴 Horse Power',         pool: 'horse',      required: true },
      { label: '📜 Closing Wisdom',      pool: 'wisdom',     required: true },
    ],
  },
  {
    title: '🧧 Auspicious Wishes Scroll',
    intro: 'Blessings from {name} in Glasgow',
    sections: [
      { label: '🐴 Year of the Horse',   pool: 'horse',      required: true },
      { label: '💰 Fortune & Wealth',    pool: 'prosperity', required: true },
      { label: '🧧 Classic Blessing',    pool: 'blessing',   required: true },
      { label: '🐴 Horse Gallops On',    pool: 'horse',      required: true },
      { label: '🏮 Peace & Harmony',     pool: 'harmony',    required: true },
      { label: '📜 Parting Wisdom',      pool: 'wisdom',     required: true },
    ],
  },
];

// ─── Category Pools Mapping ─────────────────────────────────
const PHRASE_POOLS = {
  horse: HORSE_PHRASES,
  blessing: BLESSING_PHRASES,
  prosperity: PROSPERITY_PHRASES,
  harmony: HARMONY_PHRASES,
  wisdom: WISDOM_PHRASES,
};

// ─── Avatars ────────────────────────────────────────────────
const AVATARS = ['🐴', '🏇', '🎠', '🐎', '🎑', '🏮', '🧧', '🎆', '🎊', '🎋', '🌸', '🍊', '💰', '🥟', '🎏', '🎐'];
